all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ubuntu
    ansible_become: true
    security_mode: ssl
preflight:
  hosts:
    ec2-18-130-205-109.eu-west-2.compute.amazonaws.com:
    ec2-3-10-4-175.eu-west-2.compute.amazonaws.com:
    ec2-3-8-186-17.eu-west-2.compute.amazonaws.com:
    ec2-52-56-136-88.eu-west-2.compute.amazonaws.com:
zookeeper:
  hosts:
    ec2-18-130-205-109.eu-west-2.compute.amazonaws.com:
    ec2-3-10-4-175.eu-west-2.compute.amazonaws.com:
    ec2-3-8-186-17.eu-west-2.compute.amazonaws.com:
kafka_broker:
  hosts:
    ec2-18-130-205-109.eu-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 1
    ec2-3-10-4-175.eu-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 2
    ec2-3-8-186-17.eu-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 3
schema_registry:
  hosts:
    ec2-52-56-136-88.eu-west-2.compute.amazonaws.com:
control_center:
  hosts:
    ec2-52-56-136-88.eu-west-2.compute.amazonaws.com:
      control_center:
        properties:
          confluent.controlcenter.connect.cluster: ec2-52-56-136-88.eu-west-2.compute.amazonaws.com:8083
# kafka_connect:
#   hosts:
#     ec2-52-56-136-88.eu-west-2.compute.amazonaws.com:
kafka_rest:
  hosts:
    ec2-52-56-136-88.eu-west-2.compute.amazonaws.com:
ksql:
  hosts:
    ec2-52-56-136-88.eu-west-2.compute.amazonaws.com:
