all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ubuntu
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    ec2-3-9-197-210.eu-west-2.compute.amazonaws.com:
    ec2-3-9-226-235.eu-west-2.compute.amazonaws.com:
    ec2-3-9-240-232.eu-west-2.compute.amazonaws.com:
    ec2-35-178-215-243.eu-west-2.compute.amazonaws.com:
zookeeper:
  hosts:
    ec2-3-9-197-210.eu-west-2.compute.amazonaws.com:
    ec2-3-9-226-235.eu-west-2.compute.amazonaws.com:
    ec2-3-9-240-232.eu-west-2.compute.amazonaws.com:
broker:
  hosts:
    ec2-3-9-197-210.eu-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 1
    ec2-3-9-226-235.eu-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 2
    ec2-3-9-240-232.eu-west-2.compute.amazonaws.com:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    ec2-35-178-215-243.eu-west-2.compute.amazonaws.com:
control-center:
  hosts:
    ec2-35-178-215-243.eu-west-2.compute.amazonaws.com:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: ec2-35-178-215-243.eu-west-2.compute.amazonaws.com:8083
connect-distributed:
  hosts:
    ec2-35-178-215-243.eu-west-2.compute.amazonaws.com:
kafka-rest:
  hosts:
    ec2-35-178-215-243.eu-west-2.compute.amazonaws.com:
ksql:
  hosts:
    ec2-35-178-215-243.eu-west-2.compute.amazonaws.com:
