all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ubuntu
    ansible_become: true
    security_mode: ssl
preflight:
  hosts:
    ec2-18-130-238-33.eu-west-2.compute.amazonaws.com:
    ec2-3-8-167-154.eu-west-2.compute.amazonaws.com:
    ec2-3-8-96-126.eu-west-2.compute.amazonaws.com:
    ec2-35-178-191-203.eu-west-2.compute.amazonaws.com:
zookeeper:
  hosts:
    ec2-18-130-238-33.eu-west-2.compute.amazonaws.com:
    ec2-3-8-167-154.eu-west-2.compute.amazonaws.com:
    ec2-3-8-96-126.eu-west-2.compute.amazonaws.com:
kafka_broker:
  hosts:
    ec2-18-130-238-33.eu-west-2.compute.amazonaws.com:
      kafka_broker:
        properties:
          advertised.listeners: SSL://ec2-18-130-238-33.eu-west-2.compute.amazonaws.com:9092
    ec2-3-8-167-154.eu-west-2.compute.amazonaws.com:
      kafka_broker:
        properties:
          advertised.listeners: SSL://ec2-3-8-167-154.eu-west-2.compute.amazonaws.com:9092
    ec2-3-8-96-126.eu-west-2.compute.amazonaws.com:
      kafka_broker:
        properties:
          advertised.listeners: SSL://ec2-3-8-96-126.eu-west-2.compute.amazonaws.com:9092
schema_registry:
  hosts:
    ec2-35-178-191-203.eu-west-2.compute.amazonaws.com:
control_center:
  hosts:
    ec2-35-178-191-203.eu-west-2.compute.amazonaws.com:
kafka_connect:
  hosts:
    ec2-35-178-191-203.eu-west-2.compute.amazonaws.com:
kafka_rest:
  hosts:
    ec2-35-178-191-203.eu-west-2.compute.amazonaws.com:
ksql:
  hosts:
    ec2-35-178-191-203.eu-west-2.compute.amazonaws.com:
